import type { CueTypeEntry } from "./cuePropertyTypes";
import { PARAMETRIC_IMAGE_SHAPES } from "./parametricImageShapes";

// 18 cue types in index order (New Cue menu order, Flash Animation and
// 3D Animation omitted - could not be captured in the test workspace).
export const CUE_TYPES: readonly CueTypeEntry[] = [
  {
    label: "Frames (Simple)",
    uniqueProperties: [],
  },
  {
    label: "Frames (Advanced)",
    uniqueProperties: [],
  },
  {
    label: "Text",
    uniqueProperties: [
      "Image.CharAlignX",
      "Image.CharAlignY",
      "Image.CharEffDelay",
      "Image.Color",
      "Image.EnableStaticMode",
      "Image.GlobalCharTime",
      "Image.MonoSpaced",
      "Image.MultiLaser",
      "Image.PlayLoopCount",
      "Image.RangeScale",
      "Image.ScaleX",
      "Image.ScaleY",
      "Image.ScrollingSpeed",
      "Image.SpaceX",
      "Image.SpaceY",
      "Image.StaticDisplayTime",
      "Image.Text",
      "Image.TextSizeX",
      "Image.TextSizeY",
      "Image.VertOffset",
    ],
  },
  {
    label: "Shape",
    uniqueProperties: [
      "Image.AudioMode",
      "Image.BeamConnect",
      "Image.BeamRepeat",
      "Image.BeamSpeed",
      "Image.Color",
      "Image.CursorX",
      "Image.CursorY",
      "Image.CursorZ",
      "Image.EnableRecording",
      "Image.FftMode",
      "Image.Loops",
      "Image.Mode",
      "Image.NGonCount",
      "Image.PhysicsActive",
      "Image.PointCount",
      "Image.Radius",
      "Image.RecordInterval",
      "Image.ScrollSpeedX",
      "Image.ScrollSpeedY",
      "Image.ScrollSpeedZ",
      "Image.ShowCorners",
      "Image.StartShape",
    ],
  },
  {
    label: "Abstraction",
    uniqueProperties: [],
  },
  {
    label: "Classic LD2000 Abstract",
    uniqueProperties: [
      "Image.0.FreqColor",
      "Image.0.FreqMOD1",
      "Image.0.FreqMOD2",
      "Image.0.FreqX1",
      "Image.0.FreqX2",
      "Image.0.FreqX3",
      "Image.0.FreqY1",
      "Image.0.FreqY2",
      "Image.0.FreqY3",
      "Image.0.FreqZ1",
      "Image.0.FreqZ2",
      "Image.0.FreqZ3",
      "Image.0.SizeMOD1",
      "Image.0.SizeMOD2",
      "Image.0.SizeX1",
      "Image.0.SizeX2",
      "Image.0.SizeX3",
      "Image.0.SizeY1",
      "Image.0.SizeY2",
      "Image.0.SizeY3",
      "Image.0.SizeZ1",
      "Image.0.SizeZ2",
      "Image.0.SizeZ3",
      "Image.0.WaveMOD1",
      "Image.0.WaveMOD2",
      "Image.0.WaveOSC1",
      "Image.0.WaveOSC2",
      "Image.0.WaveOSC3",
    ],
  },
  {
    label: "Parametric-Image",
    // Properties shared by ALL 33 shapes (beyond the 130 common cue props).
    uniqueProperties: ["Image.Effect.ChasePeriod", "Image.Effect.ChaseTimeMode"],
    shapes: PARAMETRIC_IMAGE_SHAPES,
  },
  {
    label: "Clock",
    uniqueProperties: [],
  },
  {
    label: "Synthesized Image",
    uniqueProperties: [
      "Image.LIST.0.AngleX",
      "Image.LIST.0.AngleY",
      "Image.LIST.0.AngleZ",
      "Image.LIST.0.Effect.ChasePeriod",
      "Image.LIST.0.Effect.ChaseTimeMode",
      "Image.LIST.0.Effect.ClockLimit",
      "Image.LIST.0.Effect.ClockShift",
      "Image.LIST.0.Effect.EnableClockLimit",
      "Image.LIST.0.Effect.EnableMetroLimit",
      "Image.LIST.0.Effect.MetroLimit",
      "Image.LIST.0.Effect.MetroShift",
      "Image.LIST.0.Effect.Name",
      "Image.LIST.0.Effect.Zone",
      "Image.LIST.0.Effect.ZoneMode",
      "Image.LIST.0.Image.AudioMode",
      "Image.LIST.0.Image.BeamConnect",
      "Image.LIST.0.Image.BeamRepeat",
      "Image.LIST.0.Image.BeamSpeed",
      "Image.LIST.0.Image.Color",
      "Image.LIST.0.Image.CursorX",
      "Image.LIST.0.Image.CursorY",
      "Image.LIST.0.Image.CursorZ",
      "Image.LIST.0.Image.EnableRecording",
      "Image.LIST.0.Image.FftMode",
      "Image.LIST.0.Image.Loops",
      "Image.LIST.0.Image.Mode",
      "Image.LIST.0.Image.NGonCount",
      "Image.LIST.0.Image.PhysicsActive",
      "Image.LIST.0.Image.PointCount",
      "Image.LIST.0.Image.Radius",
      "Image.LIST.0.Image.RecordInterval",
      "Image.LIST.0.Image.ScrollSpeedX",
      "Image.LIST.0.Image.ScrollSpeedY",
      "Image.LIST.0.Image.ScrollSpeedZ",
      "Image.LIST.0.Image.ShowCorners",
      "Image.LIST.0.Image.StartShape",
      "Image.LIST.0.Muted",
      "Image.LIST.0.PositionX",
      "Image.LIST.0.PositionY",
      "Image.LIST.0.PositionZ",
      "Image.LIST.0.SizeX",
      "Image.LIST.0.SizeY",
      "Image.LIST.0.SizeZ",
    ],
  },
  {
    label: "Node-Image",
    uniqueProperties: [],
  },
  {
    label: "Particles",
    uniqueProperties: [
      "Image.BounceMaxX",
      "Image.BounceMaxY",
      "Image.BounceMaxZ",
      "Image.BounceMinX",
      "Image.BounceMinY",
      "Image.BounceMinZ",
      "Image.Brightness",
      "Image.CenterX",
      "Image.CenterXSpread",
      "Image.CenterY",
      "Image.CenterYSpread",
      "Image.CenterZ",
      "Image.CenterZSpread",
      "Image.Count",
      "Image.Deceleration",
      "Image.DirectionSpread",
      "Image.DirectionXY",
      "Image.DirectionZ",
      "Image.Duration",
      "Image.DurationSpread",
      "Image.Gravity",
      "Image.Hue",
      "Image.HueSpread",
      "Image.MaxX",
      "Image.MaxY",
      "Image.MaxZ",
      "Image.MinX",
      "Image.MinY",
      "Image.MinZ",
      "Image.MotionDeceleration",
      "Image.MotionSpeed",
      "Image.MotionSpeedSpread",
      "Image.PointCount",
      "Image.RotoDeceleration",
      "Image.RotoSpeed",
      "Image.RotoSpeedSpread",
      "Image.Saturation",
      "Image.Speed",
      "Image.SpeedSpread",
      "Image.StartLag",
    ],
  },
  {
    label: "FIFO Image",
    uniqueProperties: [
      "Image.AngleX",
      "Image.AngleY",
      "Image.AngleZ",
      "Image.AutoRecord",
      "Image.Count",
      "Image.CursorColor",
      "Image.CursorX",
      "Image.CursorY",
      "Image.CursorZ",
      "Image.EnableRecord",
      "Image.PointCount",
      "Image.PosX",
      "Image.PosY",
      "Image.PosZ",
      "Image.RecordInterval",
      "Image.SizeX",
      "Image.SizeY",
      "Image.SizeZ",
    ],
  },
  {
    label: "Write-Out / Path following",
    uniqueProperties: [],
  },
  {
    label: "Object Animator",
    uniqueProperties: [
      "Ani.0.MaxValue",
      "Ani.0.MinValue",
      "Ani.0.Muted",
      "Ani.0.Period",
      "Ani.0.PreventReroute",
      "Ani.0.Solo",
      "Ani.0.WavePhase",
      "Ani.0.WaveStillState",
      "Ani.0.tsBuddy",
      "Ani.0.tsGrouping",
      "Ani.0.tsPhase",
      "Ani.0.tsShiftBetweenItems",
      "Ani.0.tsStretchGrouping",
      "Ani.0.tsWindowTime",
    ],
  },
  {
    label: "Real Time Video Tracer",
    uniqueProperties: [],
  },
  {
    label: "DMX-Image",
    uniqueProperties: [],
  },
  {
    label: "Multi Effect",
    uniqueProperties: [],
  },
  {
    label: "Destination",
    uniqueProperties: [],
  },
];
