import type { ParametricImageShape } from "./cuePropertyTypes";

// 33 Parametric-Image shapes captured from WS page 2.
// uniqueProperties lists properties specific to that shape beyond the 2 shared
// Parametric-Image props (Image.Effect.ChasePeriod, Image.Effect.ChaseTimeMode)
// and the 130 common cue properties.
export const PARAMETRIC_IMAGE_SHAPES: readonly ParametricImageShape[] = [
  {
    label: "wave",
    uniqueProperties: [
      "Image.Amplitude",
      "Image.Balance",
      "Image.Brightness",
      "Image.CenterX",
      "Image.CenterY",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Periods",
      "Image.Phase",
      "Image.PointCount",
      "Image.Saturation",
      "Image.Width",
    ],
  },
  {
    label: "beam",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.PointCount",
      "Image.Saturation",
      "Image.X",
      "Image.Y",
      "Image.Z",
    ],
  },
  {
    label: "centered line",
    uniqueProperties: [
      "Image.AnchBrigh",
      "Image.AnchHue",
      "Image.AnchSat",
      "Image.Angle",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndAnch",
      "Image.LineBright",
      "Image.LineHue",
      "Image.LineSat",
      "Image.PointCount",
      "Image.Size",
      "Image.StartAnch",
    ],
  },
  {
    label: "horizontal lines",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Point/Line",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "polygon",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Corners",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Saturation",
      "Image.Size",
      "Image.StartAngle",
    ],
  },
  {
    label: "spiral",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndRadius",
      "Image.Hue",
      "Image.Loops",
      "Image.Points",
      "Image.Saturation",
      "Image.StartAngle",
      "Image.StartRadius",
    ],
  },
  {
    label: "line",
    uniqueProperties: [
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndAnch",
      "Image.EndX",
      "Image.EndY",
      "Image.EndZ",
      "Image.LineBright",
      "Image.LineHue",
      "Image.LineSat",
      "Image.PointCount",
      "Image.StartAnch",
      "Image.StartX",
      "Image.StartY",
      "Image.StartZ",
    ],
  },
  {
    label: "vector",
    uniqueProperties: [
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndX",
      "Image.EndY",
      "Image.EndZ",
      "Image.LineBright",
      "Image.LineHue",
      "Image.LineSat",
      "Image.StartX",
      "Image.StartY",
      "Image.StartZ",
    ],
  },
  {
    label: "rectangle",
    uniqueProperties: [
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndX",
      "Image.EndY",
      "Image.EndZ",
      "Image.LineBright",
      "Image.LineHue",
      "Image.LineSat",
      "Image.MiddleAnch",
      "Image.PointCount",
      "Image.StartAnch",
      "Image.StartX",
      "Image.StartY",
      "Image.StartZ",
    ],
  },
  {
    label: "elipse",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.FinsihOverlap",
      "Image.Hue",
      "Image.Points",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
      "Image.StartOverlap",
    ],
  },
  {
    label: "elipse multi-loop",
    uniqueProperties: [
      "Image.BlankPoints",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Points",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
      "Image.Turns(%)",
    ],
  },
  {
    label: "arc by two points",
    uniqueProperties: [
      "Image.Brightness",
      "Image.CenterX",
      "Image.CenterY",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndAnch",
      "Image.EndAngle",
      "Image.Hue",
      "Image.PointCount",
      "Image.RadiusX",
      "Image.RadiusY",
      "Image.Saturation",
      "Image.StartAnch",
      "Image.StartAngle",
    ],
  },
  {
    label: "slice",
    uniqueProperties: [
      "Image.AngleAmp",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Periods",
      "Image.PointCount",
      "Image.Radius",
    ],
  },
  {
    label: "centered spiral",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Hue",
      "Image.Loops",
      "Image.Points",
      "Image.Radius",
      "Image.Saturation",
      "Image.StartAngle",
    ],
  },
  {
    label: "snow star",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.Size",
      "Image.StartAngle",
    ],
  },
  {
    label: "cross star",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Corners",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Saturation",
      "Image.Size",
      "Image.StartAngle",
    ],
  },
  {
    label: "poly star",
    uniqueProperties: [
      "Image.AnchorsIn",
      "Image.AnchorsOut",
      "Image.Brightness",
      "Image.Corners",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.ExternalR",
      "Image.Hue",
      "Image.InternalR",
      "Image.Saturation",
      "Image.StartAngle",
    ],
  },
  {
    label: "sphere spiral",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Loops",
      "Image.Points",
      "Image.Saturation",
      "Image.Size(%)",
    ],
  },
  {
    label: "cylinder spiral",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Loops",
      "Image.Points",
      "Image.Saturation",
      "Image.Size(%)",
    ],
  },
  {
    label: "center cone",
    uniqueProperties: [
      "Image.AngleAmp",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Periods",
      "Image.PointCount",
      "Image.Radius",
      "Image.RotationX",
      "Image.RotationY",
      "Image.RotationZ",
      "Image.Saturation",
    ],
  },
  {
    label: "arrow",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.HeadSize",
      "Image.Inner",
      "Image.TailSize",
    ],
  },
  {
    label: "horizontal vectors",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "vertical vectors",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "vector grid",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "vertical lines",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Point/Line",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "grid point oriented",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "dot grid",
    uniqueProperties: [
      "Image.Brightness",
      "Image.CountX",
      "Image.CountY",
      "Image.DX",
      "Image.DY",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "random dots",
    uniqueProperties: [
      "Image.AddPerStep",
      "Image.BeamPower",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Points",
      "Image.XCoverage",
      "Image.YCoverage",
      "Image.ZCoverage",
    ],
  },
  {
    label: "lightning",
    uniqueProperties: [
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Points",
    ],
  },
  {
    label: "random lines",
    uniqueProperties: [
      "Image.AddPerStep",
      "Image.CornerPower",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Lines",
      "Image.XCoverage",
      "Image.YCoverage",
      "Image.ZCoverage",
    ],
  },
  {
    label: "rectangular lines",
    uniqueProperties: [
      "Image.AddPerStep",
      "Image.CornerPower",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Lines",
      "Image.XCoverage",
      "Image.YCoverage",
      "Image.ZPosition",
    ],
  },
  {
    label: "random shapes",
    uniqueProperties: [
      "Image.AddPerStep",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Shape",
      "Image.ShapeCount",
      "Image.Size",
      "Image.XCoverage",
      "Image.YCoverage",
      "Image.ZCoverage",
    ],
  },
  {
    label: "cube",
    uniqueProperties: [
      "Image.Bright",
      "Image.CenterX",
      "Image.CenterY",
      "Image.CenterZ",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Sat",
      "Image.SizeX",
      "Image.SizeY",
      "Image.SizeZ",
    ],
  },
];
