// BEYOND cue type hierarchy from BEYOND 5.5.0 Build 2044. Index order matches
// the "New Cue" menu minus Flash Animation and 3D Animation, which could not
// be added to the source workspace.
//
// Parametric Image shapes from WS page 2. Each shape exposes a distinct set of
// Image.* properties in addition to the 2 props shared by all Parametric Image
// shapes and the 130 common cue properties.

export interface CueTypeEntry {
  readonly label: string;
  readonly uniqueProperties: readonly string[];
  readonly shapes?: readonly ParametricImageShape[];
}

export interface ParametricImageShape {
  readonly label: string;
  readonly uniqueProperties: readonly string[];
}

// 130 properties present on every cue type regardless of content type.
export const CUE_COMMON_PROPERTIES: readonly string[] = [
  "Alpha",
  "AnimationSpeed",
  "BeamBrush",
  "Blue",
  "Brightness",
  "Caption",
  "CaptionColor",
  "ClickMode",
  "ColorSlider",
  "ContainEndScript",
  "ContainStartScript",
  "CueType",
  "Effect.ChasePeriod",
  "Effect.ChaseTimeMode",
  "Effect.ClockLimit",
  "Effect.ClockShift",
  "Effect.EnableClockLimit",
  "Effect.EnableMetroLimit",
  "Effect.MetroLimit",
  "Effect.MetroShift",
  "Effect.Name",
  "Effect.Zone",
  "Effect.ZoneMode",
  "FX1",
  "FX1Action",
  "FX1Mute",
  "FX1TimeMulClock",
  "FX1TimeMulMetro",
  "FX1TimeScaleClock",
  "FX1TimeScaleMetro",
  "FX1TimeShiftClock",
  "FX1TimeShiftMetro",
  "FX2",
  "FX2Action",
  "FX2Mute",
  "FX2TimeMulClock",
  "FX2TimeMulMetro",
  "FX2TimeScaleClock",
  "FX2TimeScaleMetro",
  "FX2TimeShiftClock",
  "FX2TimeShiftMetro",
  "FX3",
  "FX3Action",
  "FX3Mute",
  "FX3TimeMulClock",
  "FX3TimeMulMetro",
  "FX3TimeScaleClock",
  "FX3TimeScaleMetro",
  "FX3TimeShiftClock",
  "FX3TimeShiftMetro",
  "FX4",
  "FX4Action",
  "FX4Mute",
  "FX4TimeMulClock",
  "FX4TimeMulMetro",
  "FX4TimeScaleClock",
  "FX4TimeScaleMetro",
  "FX4TimeShiftClock",
  "FX4TimeShiftMetro",
  "FX5",
  "FX5Action",
  "FX5Mute",
  "FX5TimeMulClock",
  "FX5TimeMulMetro",
  "FX5TimeScaleClock",
  "FX5TimeScaleMetro",
  "FX5TimeShiftClock",
  "FX5TimeShiftMetro",
  "FX6",
  "FX6Action",
  "FX6Mute",
  "FX6TimeMulClock",
  "FX6TimeMulMetro",
  "FX6TimeScaleClock",
  "FX6TimeScaleMetro",
  "FX6TimeShiftClock",
  "FX6TimeShiftMetro",
  "FX7",
  "FX7Action",
  "FX7Mute",
  "FX7TimeMulClock",
  "FX7TimeMulMetro",
  "FX7TimeScaleClock",
  "FX7TimeScaleMetro",
  "FX7TimeShiftClock",
  "FX7TimeShiftMetro",
  "FX8",
  "FX8Action",
  "FX8Mute",
  "FX8TimeMulClock",
  "FX8TimeMulMetro",
  "FX8TimeScaleClock",
  "FX8TimeScaleMetro",
  "FX8TimeShiftClock",
  "FX8TimeShiftMetro",
  "Green",
  "Hue",
  "HueShift",
  "Pan",
  "PosX",
  "PosY",
  "PosZ",
  "PositionX",
  "PositionY",
  "PositionZ",
  "RGBColor",
  "Red",
  "RotoAccX",
  "RotoAccY",
  "RotoAccZ",
  "RotoAngleX",
  "RotoAngleY",
  "RotoAngleZ",
  "RotoSpeedX",
  "RotoSpeedY",
  "RotoSpeedZ",
  "SatShift",
  "Saturation",
  "ScanRate",
  "SizeX",
  "SizeY",
  "SizeZ",
  "StrobeAcc",
  "StrobeSpeed",
  "Tilt",
  "VisiblePointStart",
  "VisiblePoints",
  "VisiblePointsEnd",
  "VisiblePointsStart",
  "Zoom",
];

// 33 Parametric-Image shapes captured from WS page 2.
// uniqueProperties lists properties specific to that shape beyond the 2 shared
// Parametric-Image props (Image.Effect.ChasePeriod, Image.Effect.ChaseTimeMode)
// and the 130 common cue properties.
const PARAMETRIC_IMAGE_SHAPES: readonly ParametricImageShape[] = [
  {
    label: "wave",
    uniqueProperties: [
      "Image.Amplitude",
      "Image.Balance",
      "Image.Brightness",
      "Image.CenterX",
      "Image.CenterY",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Periods",
      "Image.Phase",
      "Image.PointCount",
      "Image.Saturation",
      "Image.Width",
    ],
  },
  {
    label: "beam",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.PointCount",
      "Image.Saturation",
      "Image.X",
      "Image.Y",
      "Image.Z",
    ],
  },
  {
    label: "centered line",
    uniqueProperties: [
      "Image.AnchBrigh",
      "Image.AnchHue",
      "Image.AnchSat",
      "Image.Angle",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndAnch",
      "Image.LineBright",
      "Image.LineHue",
      "Image.LineSat",
      "Image.PointCount",
      "Image.Size",
      "Image.StartAnch",
    ],
  },
  {
    label: "horizontal lines",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Point/Line",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "polygon",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Corners",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Saturation",
      "Image.Size",
      "Image.StartAngle",
    ],
  },
  {
    label: "spiral",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndRadius",
      "Image.Hue",
      "Image.Loops",
      "Image.Points",
      "Image.Saturation",
      "Image.StartAngle",
      "Image.StartRadius",
    ],
  },
  {
    label: "line",
    uniqueProperties: [
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndAnch",
      "Image.EndX",
      "Image.EndY",
      "Image.EndZ",
      "Image.LineBright",
      "Image.LineHue",
      "Image.LineSat",
      "Image.PointCount",
      "Image.StartAnch",
      "Image.StartX",
      "Image.StartY",
      "Image.StartZ",
    ],
  },
  {
    label: "vector",
    uniqueProperties: [
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndX",
      "Image.EndY",
      "Image.EndZ",
      "Image.LineBright",
      "Image.LineHue",
      "Image.LineSat",
      "Image.StartX",
      "Image.StartY",
      "Image.StartZ",
    ],
  },
  {
    label: "rectangle",
    uniqueProperties: [
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndX",
      "Image.EndY",
      "Image.EndZ",
      "Image.LineBright",
      "Image.LineHue",
      "Image.LineSat",
      "Image.MiddleAnch",
      "Image.PointCount",
      "Image.StartAnch",
      "Image.StartX",
      "Image.StartY",
      "Image.StartZ",
    ],
  },
  {
    label: "elipse",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.FinsihOverlap",
      "Image.Hue",
      "Image.Points",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
      "Image.StartOverlap",
    ],
  },
  {
    label: "elipse multi-loop",
    uniqueProperties: [
      "Image.BlankPoints",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Points",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
      "Image.Turns(%)",
    ],
  },
  {
    label: "arc by two points",
    uniqueProperties: [
      "Image.Brightness",
      "Image.CenterX",
      "Image.CenterY",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.EndAnch",
      "Image.EndAngle",
      "Image.Hue",
      "Image.PointCount",
      "Image.RadiusX",
      "Image.RadiusY",
      "Image.Saturation",
      "Image.StartAnch",
      "Image.StartAngle",
    ],
  },
  {
    label: "slice",
    uniqueProperties: [
      "Image.AngleAmp",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Periods",
      "Image.PointCount",
      "Image.Radius",
    ],
  },
  {
    label: "centered spiral",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Hue",
      "Image.Loops",
      "Image.Points",
      "Image.Radius",
      "Image.Saturation",
      "Image.StartAngle",
    ],
  },
  {
    label: "snow star",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.Size",
      "Image.StartAngle",
    ],
  },
  {
    label: "cross star",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Corners",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Saturation",
      "Image.Size",
      "Image.StartAngle",
    ],
  },
  {
    label: "poly star",
    uniqueProperties: [
      "Image.AnchorsIn",
      "Image.AnchorsOut",
      "Image.Brightness",
      "Image.Corners",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.ExternalR",
      "Image.Hue",
      "Image.InternalR",
      "Image.Saturation",
      "Image.StartAngle",
    ],
  },
  {
    label: "sphere spiral",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Loops",
      "Image.Points",
      "Image.Saturation",
      "Image.Size(%)",
    ],
  },
  {
    label: "cylinder spiral",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Loops",
      "Image.Points",
      "Image.Saturation",
      "Image.Size(%)",
    ],
  },
  {
    label: "center cone",
    uniqueProperties: [
      "Image.AngleAmp",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Periods",
      "Image.PointCount",
      "Image.Radius",
      "Image.RotationX",
      "Image.RotationY",
      "Image.RotationZ",
      "Image.Saturation",
    ],
  },
  {
    label: "arrow",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.HeadSize",
      "Image.Inner",
      "Image.TailSize",
    ],
  },
  {
    label: "horizontal vectors",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "vertical vectors",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "vector grid",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "vertical lines",
    uniqueProperties: [
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Point/Line",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "grid point oriented",
    uniqueProperties: [
      "Image.Anchors",
      "Image.Brightness",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Lines",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "dot grid",
    uniqueProperties: [
      "Image.Brightness",
      "Image.CountX",
      "Image.CountY",
      "Image.DX",
      "Image.DY",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Saturation",
      "Image.SizeX",
      "Image.SizeY",
    ],
  },
  {
    label: "random dots",
    uniqueProperties: [
      "Image.AddPerStep",
      "Image.BeamPower",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Points",
      "Image.XCoverage",
      "Image.YCoverage",
      "Image.ZCoverage",
    ],
  },
  {
    label: "lightning",
    uniqueProperties: [
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Points",
    ],
  },
  {
    label: "random lines",
    uniqueProperties: [
      "Image.AddPerStep",
      "Image.CornerPower",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Lines",
      "Image.XCoverage",
      "Image.YCoverage",
      "Image.ZCoverage",
    ],
  },
  {
    label: "rectangular lines",
    uniqueProperties: [
      "Image.AddPerStep",
      "Image.CornerPower",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Lines",
      "Image.XCoverage",
      "Image.YCoverage",
      "Image.ZPosition",
    ],
  },
  {
    label: "random shapes",
    uniqueProperties: [
      "Image.AddPerStep",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Shape",
      "Image.ShapeCount",
      "Image.Size",
      "Image.XCoverage",
      "Image.YCoverage",
      "Image.ZCoverage",
    ],
  },
  {
    label: "cube",
    uniqueProperties: [
      "Image.Bright",
      "Image.CenterX",
      "Image.CenterY",
      "Image.CenterZ",
      "Image.Effect.ClockLimit",
      "Image.Effect.ClockShift",
      "Image.Effect.EnableClockLimit",
      "Image.Effect.EnableMetroLimit",
      "Image.Effect.MetroLimit",
      "Image.Effect.MetroShift",
      "Image.Effect.Name",
      "Image.Effect.Zone",
      "Image.Effect.ZoneMode",
      "Image.Hue",
      "Image.Sat",
      "Image.SizeX",
      "Image.SizeY",
      "Image.SizeZ",
    ],
  },
];

// 18 cue types in index order (New Cue menu order, Flash Animation and
// 3D Animation omitted — could not be captured in the test workspace).
export const CUE_TYPES: readonly CueTypeEntry[] = [
  {
    label: "Frames (Simple)",
    uniqueProperties: [],
  },
  {
    label: "Frames (Advanced)",
    uniqueProperties: [],
  },
  {
    label: "Text",
    uniqueProperties: [
      "Image.CharAlignX",
      "Image.CharAlignY",
      "Image.CharEffDelay",
      "Image.Color",
      "Image.EnableStaticMode",
      "Image.GlobalCharTime",
      "Image.MonoSpaced",
      "Image.MultiLaser",
      "Image.PlayLoopCount",
      "Image.RangeScale",
      "Image.ScaleX",
      "Image.ScaleY",
      "Image.ScrollingSpeed",
      "Image.SpaceX",
      "Image.SpaceY",
      "Image.StaticDisplayTime",
      "Image.Text",
      "Image.TextSizeX",
      "Image.TextSizeY",
      "Image.VertOffset",
    ],
  },
  {
    label: "Shape",
    uniqueProperties: [
      "Image.AudioMode",
      "Image.BeamConnect",
      "Image.BeamRepeat",
      "Image.BeamSpeed",
      "Image.Color",
      "Image.CursorX",
      "Image.CursorY",
      "Image.CursorZ",
      "Image.EnableRecording",
      "Image.FftMode",
      "Image.Loops",
      "Image.Mode",
      "Image.NGonCount",
      "Image.PhysicsActive",
      "Image.PointCount",
      "Image.Radius",
      "Image.RecordInterval",
      "Image.ScrollSpeedX",
      "Image.ScrollSpeedY",
      "Image.ScrollSpeedZ",
      "Image.ShowCorners",
      "Image.StartShape",
    ],
  },
  {
    label: "Abstraction",
    uniqueProperties: [],
  },
  {
    label: "Classic LD2000 Abstract",
    uniqueProperties: [
      "Image.0.FreqColor",
      "Image.0.FreqMOD1",
      "Image.0.FreqMOD2",
      "Image.0.FreqX1",
      "Image.0.FreqX2",
      "Image.0.FreqX3",
      "Image.0.FreqY1",
      "Image.0.FreqY2",
      "Image.0.FreqY3",
      "Image.0.FreqZ1",
      "Image.0.FreqZ2",
      "Image.0.FreqZ3",
      "Image.0.SizeMOD1",
      "Image.0.SizeMOD2",
      "Image.0.SizeX1",
      "Image.0.SizeX2",
      "Image.0.SizeX3",
      "Image.0.SizeY1",
      "Image.0.SizeY2",
      "Image.0.SizeY3",
      "Image.0.SizeZ1",
      "Image.0.SizeZ2",
      "Image.0.SizeZ3",
      "Image.0.WaveMOD1",
      "Image.0.WaveMOD2",
      "Image.0.WaveOSC1",
      "Image.0.WaveOSC2",
      "Image.0.WaveOSC3",
    ],
  },
  {
    label: "Parametric-Image",
    // Properties shared by ALL 33 shapes (beyond the 130 common cue props).
    uniqueProperties: ["Image.Effect.ChasePeriod", "Image.Effect.ChaseTimeMode"],
    shapes: PARAMETRIC_IMAGE_SHAPES,
  },
  {
    label: "Clock",
    uniqueProperties: [],
  },
  {
    label: "Synthesized Image",
    uniqueProperties: [
      "Image.LIST.0.AngleX",
      "Image.LIST.0.AngleY",
      "Image.LIST.0.AngleZ",
      "Image.LIST.0.Effect.ChasePeriod",
      "Image.LIST.0.Effect.ChaseTimeMode",
      "Image.LIST.0.Effect.ClockLimit",
      "Image.LIST.0.Effect.ClockShift",
      "Image.LIST.0.Effect.EnableClockLimit",
      "Image.LIST.0.Effect.EnableMetroLimit",
      "Image.LIST.0.Effect.MetroLimit",
      "Image.LIST.0.Effect.MetroShift",
      "Image.LIST.0.Effect.Name",
      "Image.LIST.0.Effect.Zone",
      "Image.LIST.0.Effect.ZoneMode",
      "Image.LIST.0.Image.AudioMode",
      "Image.LIST.0.Image.BeamConnect",
      "Image.LIST.0.Image.BeamRepeat",
      "Image.LIST.0.Image.BeamSpeed",
      "Image.LIST.0.Image.Color",
      "Image.LIST.0.Image.CursorX",
      "Image.LIST.0.Image.CursorY",
      "Image.LIST.0.Image.CursorZ",
      "Image.LIST.0.Image.EnableRecording",
      "Image.LIST.0.Image.FftMode",
      "Image.LIST.0.Image.Loops",
      "Image.LIST.0.Image.Mode",
      "Image.LIST.0.Image.NGonCount",
      "Image.LIST.0.Image.PhysicsActive",
      "Image.LIST.0.Image.PointCount",
      "Image.LIST.0.Image.Radius",
      "Image.LIST.0.Image.RecordInterval",
      "Image.LIST.0.Image.ScrollSpeedX",
      "Image.LIST.0.Image.ScrollSpeedY",
      "Image.LIST.0.Image.ScrollSpeedZ",
      "Image.LIST.0.Image.ShowCorners",
      "Image.LIST.0.Image.StartShape",
      "Image.LIST.0.Muted",
      "Image.LIST.0.PositionX",
      "Image.LIST.0.PositionY",
      "Image.LIST.0.PositionZ",
      "Image.LIST.0.SizeX",
      "Image.LIST.0.SizeY",
      "Image.LIST.0.SizeZ",
    ],
  },
  {
    label: "Node-Image",
    uniqueProperties: [],
  },
  {
    label: "Particles",
    uniqueProperties: [
      "Image.BounceMaxX",
      "Image.BounceMaxY",
      "Image.BounceMaxZ",
      "Image.BounceMinX",
      "Image.BounceMinY",
      "Image.BounceMinZ",
      "Image.Brightness",
      "Image.CenterX",
      "Image.CenterXSpread",
      "Image.CenterY",
      "Image.CenterYSpread",
      "Image.CenterZ",
      "Image.CenterZSpread",
      "Image.Count",
      "Image.Deceleration",
      "Image.DirectionSpread",
      "Image.DirectionXY",
      "Image.DirectionZ",
      "Image.Duration",
      "Image.DurationSpread",
      "Image.Gravity",
      "Image.Hue",
      "Image.HueSpread",
      "Image.MaxX",
      "Image.MaxY",
      "Image.MaxZ",
      "Image.MinX",
      "Image.MinY",
      "Image.MinZ",
      "Image.MotionDeceleration",
      "Image.MotionSpeed",
      "Image.MotionSpeedSpread",
      "Image.PointCount",
      "Image.RotoDeceleration",
      "Image.RotoSpeed",
      "Image.RotoSpeedSpread",
      "Image.Saturation",
      "Image.Speed",
      "Image.SpeedSpread",
      "Image.StartLag",
    ],
  },
  {
    label: "FIFO Image",
    uniqueProperties: [
      "Image.AngleX",
      "Image.AngleY",
      "Image.AngleZ",
      "Image.AutoRecord",
      "Image.Count",
      "Image.CursorColor",
      "Image.CursorX",
      "Image.CursorY",
      "Image.CursorZ",
      "Image.EnableRecord",
      "Image.PointCount",
      "Image.PosX",
      "Image.PosY",
      "Image.PosZ",
      "Image.RecordInterval",
      "Image.SizeX",
      "Image.SizeY",
      "Image.SizeZ",
    ],
  },
  {
    label: "Write-Out / Path following",
    uniqueProperties: [],
  },
  {
    label: "Object Animator",
    uniqueProperties: [
      "Ani.0.MaxValue",
      "Ani.0.MinValue",
      "Ani.0.Muted",
      "Ani.0.Period",
      "Ani.0.PreventReroute",
      "Ani.0.Solo",
      "Ani.0.WavePhase",
      "Ani.0.WaveStillState",
      "Ani.0.tsBuddy",
      "Ani.0.tsGrouping",
      "Ani.0.tsPhase",
      "Ani.0.tsShiftBetweenItems",
      "Ani.0.tsStretchGrouping",
      "Ani.0.tsWindowTime",
    ],
  },
  {
    label: "Real Time Video Tracer",
    uniqueProperties: [],
  },
  {
    label: "DMX-Image",
    uniqueProperties: [],
  },
  {
    label: "Multi Effect",
    uniqueProperties: [],
  },
  {
    label: "Destination",
    uniqueProperties: [],
  },
];

export function getCueTypeProperties(entry: CueTypeEntry): string[] {
  // Type-specific properties first, then common properties.
  const unique = entry.uniqueProperties.map((p) => `WS.N.N.${p}`);
  const common = CUE_COMMON_PROPERTIES.map((p) => `WS.N.N.${p}`);
  return [...unique, ...common];
}

export function getCueShapeProperties(shape: ParametricImageShape, cueEntry: CueTypeEntry): string[] {
  // Shape-specific → type-level shared → common cue properties.
  const shapeProps = shape.uniqueProperties.map((p) => `WS.N.N.${p}`);
  const typeProps = cueEntry.uniqueProperties.map((p) => `WS.N.N.${p}`);
  const common = CUE_COMMON_PROPERTIES.map((p) => `WS.N.N.${p}`);
  return [...shapeProps, ...typeProps, ...common];
}
